---
- name: Установка Zabbix Server и PostgreSQL
  hosts: host
  become: true

  tasks:
    - name: Установка PostgreSQL
      apt:
        name: postgresql
        state: present

    - name: Создание базы данных и пользователя для Zabbix
      postgresql_db:
        name: zabbix
        state: present
        login_user: postgres
      postgresql_user:
        name: zabbix
        password: zabbix
        login_user: postgres
        priv: "zabbix.*:ALL"

    - name: Установка репозитория Zabbix
      apt_repository:
        repo: deb http://repo.zabbix.com/zabbix/5.4/ubuntu bionic main
        state: present
        filename: zabbix

    - name: Добавление ключа репозитория Zabbix
      apt_key:
        url: https://repo.zabbix.com/zabbix-official-repo.key
        state: present

    - name: Установка Zabbix Server
      apt:
        name:
          - zabbix-server-pgsql
        state: present
      vars:
        zabbix_db_host: localhost
        zabbix_db_name: zabbix
        zabbix_db_user: zabbix
        zabbix_db_password: zabbix

    - name: Настройка файла конфигурации Zabbix Server
      template:
        src: templates/zabbix_server.conf
        dest: /etc/zabbix/zabbix_server.conf
        owner: root
        group: root
        mode: '0644'

    - name: Запуск Zabbix Server
      service:
        name: zabbix-server
        state: started
        enabled: true
    - name: Открытие порта 10050 для агента
      ufw:
       rule: allow
       port: 10050
       state: enabled
